/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CityCard: typeof import('./components/CityCard.vue')['default']
    CityCardHeader: typeof import('./components/CityCardHeader.vue')['default']
    CityTemperature: typeof import('./components/CityTemperature.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WeatherInfo: typeof import('./components/WeatherInfo.vue')['default']
  }
}
